name: build-v8
on: 
  push:
    branches: [main]
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - name: download transfer tool
        shell: pwsh
        run: |
          cd ~/v8
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_windows_amd64.zip","C:\transfer.zip")
          tar -xf "C:\transfer.zip" -C "C:\v8\"
