name: build-v8
on: [push]
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - id: cache
        uses: actions/cache@v2
        with:
          path: ~/v8
          key: ${{ runner.os }}
      - name: install depot_tools
        shell: pwsh
        run: |
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://storage.googleapis.com/chrome-infra/depot_tools.zip","C:\depot_tools.zip")
          mkdir "C:\depot_tools"; tar -xf "C:\depot_tools.zip" -C "C:\depot_tools\"
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo DEPOT_TOOLS_WIN_TOOLCHAIN=0 | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: set-up-gclient
        shell: cmd
        run: gclient
      - name: fetch-v8-code
        shell: pwsh
        if: steps.cache.outputs.cache-hit != 'true'
        run: mkdir ~/v8 && cd ~/v8 && fetch v8
      - name: sync-v8-code
        shell: pwsh
        if: steps.cache.outputs.cache-hit == 'true'
        run: cd ~/v8 && sync v8

