name: build-v8
on: [push]
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - name: install depot_tools
        shell: pwsh
        run: |
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://storage.googleapis.com/chrome-infra/depot_tools.zip","C:\depot_tools.zip")
          mkdir "C:\depot_tools"; tar -xf "C:\depot_tools.zip" -C "C:\depot_tools\"
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo DEPOT_TOOLS_WIN_TOOLCHAIN=0 | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: set-up-gclient
        shell: cmd
        run: gclient
      - name: fetch-v8-code
        shell: pwsh
        run: |
          mkdir ~/v8
          cd ~/v8
          fetch v8
      - name: compile
        shell: pwsh
        run: |
          cd ~/v8/v8
          echo ./tools/dev/gm.py x64.release
          dir
          dir tools/dev
          ./tools/dev/gm.py -v x64.release
          dir out
          ninja -C out/x64.release

