name: build-v8
on: 
  push:
    branches: [main]
env:
  PATCH_FLAG: true
  COMMIT: 1e4b1c521a491c7487028b7f2aec550c1b36606b
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - name: install depot_tools
        shell: pwsh
        run: |
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://storage.googleapis.com/chrome-infra/depot_tools.zip","C:\depot_tools.zip")
          mkdir "C:\depot_tools"; tar -xf "C:\depot_tools.zip" -C "C:\depot_tools\"
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo DEPOT_TOOLS_WIN_TOOLCHAIN=0 "GYP_MSVS_OVERRIDE_PATH=D:\Visual Studio\2022\Community" GYP_MSVS_VERSION=2022 GYP_GENERATORS="ninja,msvs-ninja"| Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: fetch v8
        shell: pwsh
        run: |
          cd C:\
          mkdir v8
          cd v8
          fetch v8
      
      - name: build v8
        shell: cmd
        run: |
          gclient config https://chromium.googlesource.com/v8/v8
          gclient sync -f
          
      - name: patch v8
        if: env.PATCH_FLAG=='true' and !cancenlled()
        shell: cmd
        run: |
          cd C:\v8\v8
          git reset --hard $COMMIT
        
      # - name: compile
      #   shell: pwsh
      #   run: |
      #     cd ~/v8/v8
      #     echo ./tools/dev/gm.py x64.release
      #     dir
      #     dir tools/dev
      #     python3 ./tools/dev/gm.py x64.release
      #     dir out
      - name: download transfer tool
        shell: pwsh
        run: |
          cd C:\
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_windows_amd64.zip","C:\transfer.zip")
          tar -xf "C:\transfer.zip" -C "C:\"

      - name: gz v8
        shell: pwsh
        run: |
          cd C:\
          tar -zcvf ./v8.tar.gz ./v8

      - name: upload v8
        shell: pwsh
        run: |
          cd C:\
          .\transfer muse v8.tar.gz
