name: build-v8
on: [push]
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - run: $client = new-object System.Net.WebClient; $client.DownloadFile("https://storage.googleapis.com/chrome-infra/depot_tools.zip","C:\depot_tools.zip")
      - name: Unzip
        shell: pwsh
        run: Call :UnZipFile "C:\depot_tools\" "C:\depot_tools.zip"
      - run: dir "C:\depot_tools"
