name: build-v8
on: [push]
jobs:
  build-v8:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: C:\depot_tools
          key: ${{ runner.os }}
      - name: install depot_tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          $client = new-object System.Net.WebClient; $client.DownloadFile("https://storage.googleapis.com/chrome-infra/depot_tools.zip","C:\depot_tools.zip")
          mkdir "C:\depot_tools"; tar -xf "C:\depot_tools.zip" -C "C:\depot_tools\"
      - name: update-path
        shell: pwsh
        run: |
          echo "C:\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: gclient

